### ISSUE TITLE
编译产品目录问题

### ISSUE THREAD

**Issue by BROBIRD** [Zxilly/bbr-v3-pkg#1]
https://github.com/Zxilly/bbr-v3-deb/blob/ce6befb63034a41f7959ca1259f0892de72ae8aa/.github/workflows/build.yml#L37-L42

可以考虑参考一下我这个目录（

https://github.com/BROBIRD/bbr/blob/543fc3a079fc6d560ac2e758bee39590972a67ba/.github/workflows/main.yml#L38-L48

**Comment by Zxilly** [comment]
他会扔到父目录，我打算直接在workspace root操作了
