### ISSUE TITLE
关于README中的 net.ipv4.tcp_congestion_control 配置问题

### ISSUE THREAD

**Issue by BROBIRD** [Zxilly/bbr-v3-pkg#2]
https://github.com/Zxilly/bbr-v3-deb/blob/f1b4929c51bae57cb127ec647ab7af8b90c22d48/README.md?plain=1#L14

是不是应该是 `net.ipv4.tcp_congestion_control=bbr` ？
看了下 tcp_bbr1.c 这个文件的提交记录 [net-tcp-bbr1: for testing, a copy of BBRv1](https://github.com/google/bbr/commit/f60d60e24fc60335d3a5b40f89536e24dd4a1748)   ，似乎是 BBRv1

**Comment by Zxilly** [comment]
看起来是的。。。

**Comment by Zxilly** [comment]
fix in https://github.com/Zxilly/bbr-v3-deb/commit/ac9023fc662474ed9003b1d19f71cb35b616e919
