### ISSUE TITLE
建议通过在 mainline 上打 patch 来做 bbr3

### ISSUE THREAD

**Issue by love4taylor** [Zxilly/bbr-v3-pkg#4]
Google 自己 repo 里并不会跟进上游 bugfix

https://github.com/CachyOS/kernel-patches/blob/master/6.5/0003-bbr3.patch
https://github.com/CachyOS/kernel-patches/blob/master/6.6/0003-bbr3.patch

**Comment by Zxilly** [comment]
暂时没有时间和能力去一直维护跟进主线，只是编译出来自用
