### ISSUE TITLE
bbrv3 kernel not booting up in VM

### ISSUE THREAD

**Issue by mahsan76** [Zxilly/bbr-v3-pkg#5]
Hi
I have upgraded kernel to 6.4.1 in vmware workstation, after that i downloaded the three .deb files and installed them successfully in my linux ubuntu system. ON reboot i press shift and selected bbrv3 kernel image but it is not loading and took me to linux pompt to troubleshoot.

Kindly help

**Comment by Zxilly** [comment]
It uses the kernel config from debian-cloud-kernel, maybe not working on raw machine since it lacks the necessary driver.

**Comment by mahsan76** [comment]
Will be thankful if you can provide a solution.

**Comment by Zxilly** [comment]
There's no way to fix it without log.
And the better choice is that fork this repo and replace the config with the working one on your machine, then build it yourself.

**Comment by mahsan76** [comment]
Thanks, but can you pl guide how can I fork this repository and start the compilation process. I am right now on 5.19.9 ubuntu kernel in vmware.
